# Generated by Django 5.2.1 on 2025-05-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo')], default='cod', max_length=20),
        ),
    ]
